[workspace]
members = [
    "bin/bot-client",
    "bin/controller",
    "bin/server",
]

workspace.resolver = "2"

[workspace.dependencies]
tokio = { version = "1", features = ["full"]}
signal-hook = "0.3"